extends RefCounted

const MANIFEST := "res://assets/integrity.json"

# Imported editor metadata is regenerated by Godot; hash only authored/baked data.
static func files(directory: String = "res://assets") -> Array[String]:
	var result: Array[String] = []
	for file in DirAccess.get_files_at(directory):
		var path := directory.path_join(file)
		if file.begins_with(".") or file.ends_with(".import") or file.ends_with(".uid") or path == MANIFEST:
			continue
		result.append(path)
	for child in DirAccess.get_directories_at(directory):
		if not child.begins_with("."):
			result.append_array(files(directory.path_join(child)))
	result.sort()
	return result
