// Local Godot adaptation: replace the web dark visor with eight cheek ornaments.
// Keep the source skin, eye patches, expression coordinates and physical mesh intact.
function replaceRange(s, first, last, replacement) {
 const a=s.indexOf(first), b=s.indexOf(last,a);
 if(a<0||b<0)throw Error('Source face section changed: '+first);
 return s.slice(0,a)+replacement+s.slice(b);
}
export function withOrnaments(s) {
 s=s.replace('// Source face decals, pores, nose/blush, visor bevel, nails, mouth and shading.','// Source skin and expressions with small cheek ornaments replacing the dark mask.');
 s=s.replace('uniform bool freckles=false;', 'uniform bool freckles=false;\n'+UNIFORMS);
 s=replaceRange(s,'float iwSmax(','float iwHairline',STAR);
 s=s.replace('float iwVisor = 0.0; float iwVisorH = 0.0;','float iwDecor = 0.0;');
 s=replaceRange(s,'            // ---- visor:','            // ---- mouth',DECOR);
 return s.replace('ROUGHNESS=mix(0.58,0.44,iwVisor);','ROUGHNESS=mix(0.58,0.48,iwDecor);').replace('CLEARCOAT=mix(0.04,0.12,iwVisor)+iwNail*0.15;','CLEARCOAT=0.04+iwNail*0.15;');
}
const UNIFORMS="uniform int ornament_pattern=0;\nuniform vec4 ornament_color : source_color = vec4(1.0,0.68,0.14,1.0);\nuniform vec4 ornament_pose=vec4(1.0,0.0,0.0,0.0); // scale, rotation, angle offsets\nuniform int ornament_side=0;\n";
const STAR="// Signed distance to a ten-vertex, five-point star in face-angle coordinates.\nfloat iwStar(vec2 p, float radius){\n  float nearest = 100.0;\n  bool inside = false;\n  for (int i=0; i<10; i++) {\n    float a = 1.5707963 + float(i)*0.62831853;\n    float b = a+0.62831853;\n    float ra = i%2==0 ? radius : radius*0.45;\n    float rb = i%2==0 ? radius*0.45 : radius;\n    vec2 v = vec2(cos(a),sin(a))*ra;\n    vec2 w = vec2(cos(b),sin(b))*rb;\n    nearest = min(nearest,iwSdSeg(p,v,w));\n    if ((v.y>p.y)!=(w.y>p.y)) {\n      float cross_x = v.x+(p.y-v.y)*(w.x-v.x)/(w.y-v.y);\n      if (p.x<cross_x) inside = !inside;\n    }\n  }\n  return inside ? -nearest : nearest;\n}\n";
const DECOR="            // Small independent cheek marks, below the eye patches; no bridge or mask.\n            vec2 mark = (vec2(abs(az)-0.64,el+0.24)-ornament_pose.zw)/ornament_pose.x;\n            float rot = ornament_pose.y;\n            mark = mat2(vec2(cos(rot),sin(rot)),vec2(-sin(rot),cos(rot)))*mark;\n            if (ornament_pattern==0) {\n              iwDecor = iwFill(iwStar(mark,0.105));\n            } else if (ornament_pattern==1) {\n              float stripe = min(iwSdSeg(mark,vec2(-0.065,0.035),vec2(0.065,-0.025)),\n                                 iwSdSeg(mark,vec2(-0.04,-0.035),vec2(0.055,-0.075)));\n              iwDecor = iwFill(stripe-0.012);\n            } else if (ornament_pattern==2) {\n              float bolt = min(iwSdSeg(mark,vec2(0.035,0.09),vec2(-0.045,0.0)),\n                          min(iwSdSeg(mark,vec2(-0.045,0.0),vec2(0.035,0.0)),\n                              iwSdSeg(mark,vec2(0.035,0.0),vec2(-0.035,-0.09))));\n              iwDecor = iwFill(bolt-0.014);\n            } else if (ornament_pattern==3) {\n              float wave = max(abs(mark.y-sin(mark.x*35.0)*0.025)-0.011,abs(mark.x)-0.10);\n              iwDecor = iwFill(wave);\n            } else if (ornament_pattern==4) {\n              iwDecor = iwFill((abs(mark.x)+abs(mark.y))-0.10);\n            } else if (ornament_pattern==5) {\n              float flower = 1.0;\n              for (int i=0; i<5; i++) {\n                float a = float(i)*1.256637;\n                flower = min(flower,length(mark-vec2(cos(a),sin(a))*0.055)-0.042);\n              }\n              iwDecor = iwFill(flower);\n            } else if (ornament_pattern==6) {\n              float dots = min(length(mark-vec2(-0.055,0.04))-0.025,\n                          min(length(mark-vec2(0.035,0.005))-0.032,\n                              length(mark-vec2(-0.015,-0.055))-0.021));\n              iwDecor = iwFill(dots);\n            } else {\n              iwDecor = iwFill(max(length(mark)-0.10,-(length(mark-vec2(0.045,0.025))-0.085)));\n            }\n            if (ornament_side!=0 && az*float(ornament_side)<0.0) iwDecor = 0.0;\n            diffuseColor.rgb = mix(diffuseColor.rgb,ornament_color.rgb,iwDecor*0.9);\n";
